### ISSUE TITLE
[request] Add doHover (and expose htmlWorker in monaco-editor)

### ISSUE THREAD

**Issue by AndersMad** [Microsoft/monaco-html#2]
Add `doHover` (and others?) to `htmlWorker.ts` and expose the `htmlWorker` in monaco-editor (just like js/ts workers)

It's just a few lines of code i spose :) People can add the `Hover` etc. "adapter" to out own usage code (if above is done).. Thanks!

**Comment by aeschli** [comment]
Sorry, for the late reply. I don't understand what exactly you want to achieve. What do you mean by `out own usage code`?

**Comment by AndersMad** [comment]
good question sry (early usage) - think this ask should be placed under the monaco editor instead and its a general question for accessing the other workers like CSS - I have later done this in a direct/raw method enabling auto completion etc. for CSS and style (`style="color: red"`) inside custom languages and HTML. My code seems to create a worker instead of using existing.

I'll close this..
