### ISSUE TITLE
Editor doesn't respect htmlDefaults.setOptions to turn off angular suggestions

### ISSUE THREAD

**Issue by scniro** [Microsoft/monaco-html#3]
Calling the following...

```
monaco.languages.html.htmlDefaults.setOptions({
  format: {/* [...] */}, // all defaults
  suggest: {
    angular1: false,
    html5: true,
    ionic: false,
  }
});

monaco.editor.create( // [...]
```

and am **still** getting angular suggestions. What am I doing wrong? Where are these even coming from and how can I turn them off?

[screencap](http://i.imgur.com/yYst6nI.png)

**Comment by scniro** [comment]
Including full code for reproduction


```
let options = {
  format: {
    tabSize: 2,
    insertSpaces: false,
    wrapLineLength: 120,
    unformatted: 'default": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, select, small, span, strong, sub, sup, textarea, tt, var',
    contentUnformatted: 'pre',
    indentInnerHtml: false,
    preserveNewLines: true,
    maxPreserveNewLines: null,
    indentHandlebars: false,
    endWithNewline: false,
    extraLiners: 'head, body, /html',
    wrapAttributes: 'auto'
  },
  suggest: {
    angular1: false,
    html5: true,
    ionic: false,
  }
}

// doesnt care about tab space of 2
// doesnt care about suggestions

monaco.languages.html.htmlDefaults.setOptions(options)

console.log(monaco.languages.html.htmlDefaults.options) // all looks good ????

monaco.editor.create(document.getElementById('editor'), {value: '<div>foo</div>', language: 'html', theme: 'vs-dark'});
```

**Comment by scniro** [comment]
https://github.com/Microsoft/monaco-editor/issues/433

**Comment by scniro** [comment]
I've been mucking through the build `editor.main.js` file for a while now and have discovered the following line...

    suggest:{html5:!0,angular1:!0,ionic:!0}

This translates to `true` for everything. I am suspecting this is a bug. Can you please share some more insight on this? I'll fix it myself but everything I'm at a loss with the structure of this project and what affects what, especially since this seems to actually stem from [vscode-html-languageservice](https://github.com/Microsoft/vscode-html-languageservice). Should an issue be opened there?

**Comment by scniro** [comment]
This seemingly has been reported at https://github.com/Microsoft/vscode-html-languageservice/issues/5

**Comment by aeschli** [comment]
@scniro You were right, the options didn't get passed through. Sorry for that.

**Comment by scniro** [comment]
@aeschli thanks for looking into this! I saw your changeset and I'm glad to see it was a seemingly simple fix. Would you be willing to bump and publish a new version here and at [monaco-editor/package.json](https://github.com/Microsoft/monaco-editor/blob/master/package.json#L26)?

**Comment by aeschli** [comment]
I'll talk to @alexandrudima about making a new monaco-editor release the coming days.

**Comment by scniro** [comment]
@aeschli @alexandrudima Hey guys, just checking in to see what the word is on the street for getting this fix published. Super mega eagerly awaiting this 😎
