### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LucaGabi** [Microsoft/monaco-html#4]
Hi,

   After install opening index.html file shows an editor that has only word based text completion.

And in console:
Loading "vscode-languageserver-types" failed

**Comment by alexandrudima** [comment]
This works fine for me:

**Comment by LucaGabi** [comment]
You are right, I was wrong. I expected div and tab to do autocomplete.. sorry, it works fine.

**Comment by LucaGabi** [comment]
The error I mentioned was from the other branch .. 

Can I ask for a clue on how to also have at least css autocomplete in style tag?
