### ISSUE TITLE
HTML validation is not supported

### ISSUE THREAD

**Issue by harkue** [Microsoft/monaco-html#6]
Hi, monaco-html is not supported for validation.

How can I use eslint to validate html tags and attributes?

`
doValidation(uri: string): Thenable<ls.Diagnostic[]> {
	// not yet suported
	return Promise.as([]);
}
`

**Comment by aeschli** [comment]
the service currently doesn't support validation. The request for that is: https://github.com/Microsoft/vscode-html-languageservice/issues/26
